### ISSUE TITLE
rubygems に依存しないようにしたい

### ISSUE THREAD

**Issue by tricknotes** [sapporojs/sapporojs.org#14]
全部 JavaScript で完結している方が JavaScript のコミュニティっぽくていいなぁ、と思ったり。
(とは言っても、gh-pages が便利すぎるので、 Jekyll は使いたい...)

**Comment by tricknotes** [comment]
middleman を使うことにしました。
rubygems 使っててもいいじゃんねぇ。

**Comment by ghost** [comment]
人は変わる… :movie_camera:

**Comment by ghost** [comment]
あっ
