### ISSUE TITLE
web サイトリニューアルをしたいかもしれない

### ISSUE THREAD

**Issue by tricknotes** [sapporojs/sapporojs.org#15]
Initial commit (53ddb0c77c507b2f3c48f48720f4f5140586c310) から 1年半経つので、そろそろリニューアルしてもよいのかなぁ

**Comment by tricknotes** [comment]
2年も経ったし、リニューアルするぞ〜。するぞ〜。

**Comment by tricknotes** [comment]
しているぞ〜

**Comment by tricknotes** [comment]
リニューアルしてみたので close します！

**Comment by hachiilcane** [comment]
すっきりしましたね。お疲れさまでした！

**Comment by tricknotes** [comment]
ありがとうございます!! :smile:
