### ISSUE TITLE
Joyent で動かしてた Node.js プロセスがしんでいる

### ISSUE THREAD

**Issue by tricknotes** [sapporojs/sapporojs.org#16]
以下の機能が使えなくなっています。
- 他のひとのマウスカーソルが見える
- 現在 web サイトを見ている人数が表示される

今までと同じようにするかどうかも含めて検討かなぁ。(関連: #15)
全く同じようにするとしたら、Joyent で動かしていたアプリを heroku などに置けば良さそう。

**Comment by vanx2** [comment]
よかったら[Node Ninja](http://node-ninja.com/)使って下さい。イベント等で告知して使っていただけるならすぐにマシン用意します

**Comment by tricknotes** [comment]
@vanx2 ありがたいご提案ありがとうございます！
(お返事が遅くなってしまい、大変申し訳ありません…。)

今のところ、web サーバが必要な仕組みはなくす方向で次のリニューアルを考えております。
ですので、また web サーバが必要になったタイミングでご相談させていただきたく思います。

**Comment by tricknotes** [comment]
今までの仕組みはひとまず使わないことにしたので、閉じます！
